[icons]
icons = "awesome6"

[[block]]
block = "battery"

[[block]]
block = "cpu"
format = " $icon $utilization $frequency "

[[block]]
block = "memory"

[[block]]
block = "net"
device = "wlan0"

[[block]]
block = "temperature"

[[block]]
block = "backlight"

[[block]]
block = "sound"

[[block]]
block = "time"
