vim9script

g:eskk#large_dictionary = { "path": "/usr/share/skk/SKK-JISYO.L" }
g:mapleader = " "

def g:Complete(key: string): string
	const x = col(".") - 1
	return x > 0 && getline(".")[x - 1] =~ "[0-9a-zA-Z_]" ? key : "\<tab>"
enddef

command -nargs=1 GitGrep grep <args> `git ls-files`

set autowrite
set breakindent
set cinoptions=l1,(1s,U1s,m1
set completeopt^=fuzzy,longest
set fillchars=eob:\ ,vert:│
set scrolloff=4
set shiftwidth=4
set t_RB=
set tabstop=4
set wildmode^=longest:full
set wildoptions^=fuzzy,pum

noremap Y y$
noremap U <c-r>
noremap <leader>m :make<cr>
noremap <leader>t :make! test<cr>
noremap <leader>r :make! run<cr>
inoremap <silent> <tab>   <c-r>=g:Complete("\<lt>c-n>")<cr>
inoremap <silent> <s-tab> <c-r>=g:Complete("\<lt>c-p>")<cr>

autocmd bufreadpost * normal g`"
autocmd quickfixcmdpost * cwindow | set nowrap
autocmd diffupdated * syntax off

filetype plugin indent on
syntax enable

if filereadable("Cargo.toml") || filereadable("../Cargo.toml")
	compiler! cargo
	set makeprg=RUST_BACKTRACE=1\ cargo\ $*
	noremap <leader>m :make build<cr>
	noremap <leader>R :make! run --release<cr>
	noremap <leader>T :make! test -- --test-threads=1 --nocapture<cr>
elseif filereadable("build.ninja")
	set makeprg=ninja
endif

highlight vertsplit none ctermfg=8
highlight statusline none ctermfg=15 ctermbg=8
highlight statuslinenc none ctermfg=15 ctermbg=8
highlight visual none ctermfg=15 ctermbg=4
highlight search none ctermfg=15 ctermbg=4
highlight matchparen none cterm=bold
highlight pmenu none ctermfg=15 ctermbg=8
highlight pmenusel none ctermfg=15 ctermbg=4
highlight pmenusbar none ctermfg=15 ctermbg=8
highlight pmenuthumb none ctermfg=15 ctermbg=7

highlight comment none ctermfg=243
highlight constant none ctermfg=6
highlight identifier none
highlight preproc none
highlight special none
highlight statement none ctermfg=6
highlight type none ctermfg=6
highlight title none ctermfg=6
highlight underlined none cterm=underline

if has("win32unix")
	set noswapfile
endif
